services:
  db:
    image: mysql:8.0
    container_name: pizzaria_db
    # Define a senha do root e o nome do banco que será criado ao iniciar
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizzaria_db
    # Mapeia a porta 3306 do seu computador para a 3306 do container
    ports:
      - "3306:3306"
    # Cria um volume para que seus dados não sumam quando o container parar
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: